name: Gradle CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 8512546
          # packages: 'tools platform-tools' # this is the default

      - name: Build with Gradle
        run: ./gradlew --no-daemon build

      - name: Unit Tests
        run: ./gradlew testReleaseUnitTest
